name = "LeanRPC"
version = "0.2.0"
defaultTargets = ["leanrpc"]
testDriver = "tests"

[[require]]
name = "LeanSerde"
git = "https://github.com/oOo0oOo/LeanSerde.git"
rev = "main"

[[lean_lib]]
name = "LeanRPC"

[[lean_lib]]
name = "Tests"

[[lean_exe]]
name = "leanrpc"
root = "Main"
supportInterpreter = true

[[lean_exe]]
name = "tests"
root = "Tests.TestRunner"
supportInterpreter = true